# Generated by Django 4.2.4 on 2023-08-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_filme', models.CharField(max_length=100, verbose_name='nome')),
                ('title', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.CharField(max_length=1000, verbose_name='nome')),
                ('img', models.CharField(max_length=100, verbose_name='nome')),
                ('avaliacao', models.CharField(max_length=100, verbose_name='nome')),
            ],
        ),
    ]
