# Generated by Django 4.2.4 on 2023-08-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineGuiaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='nome'),
        ),
    ]
