# Generated by Django 4.2.4 on 2023-08-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineGuiaApp', '0002_alter_filme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='similar_id',
            field=models.CharField(default=1, max_length=100, verbose_name='nome'),
            preserve_default=False,
        ),
    ]
